 [
    {
      open: 3821,
      low: 3821,
      high: 3821,
      close: 3821,
      tickType: 'doji',
      tickLength: 0,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      trend: '',
      time: '53613',
      x: 1
    },
    {
      tickLength: null,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      time: '54113',
      x: 2,
      direction: ''
    },
    {
      open: 3821,
      low: 3821,
      high: 3821,
      close: 3821,
      tickType: 'doji',
      tickLength: 0,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3821,
      time: '55613',
      x: 3,
      direction: ''
    },
    {
      tickLength: null,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      time: '6113',
      x: 4,
      direction: ''
    },
    {
      open: 3821,
      low: 3821,
      high: 3821,
      close: 3821,
      tickType: 'doji',
      tickLength: 0,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3821,
      time: '62113',
      x: 5,
      direction: ''
    },
    {
      tickLength: null,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      time: '62613',
      x: 6,
      direction: ''
    },
    {
      open: 3821,
      low: 3821,
      high: 3821,
      close: 3821,
      tickType: 'doji',
      tickLength: 0,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3821,
      time: '64613',
      x: 7,
      direction: ''
    },
    {
      tickLength: null,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      time: '65113',
      x: 8,
      direction: ''
    },
    {
      open: 3821,
      low: 3821,
      high: 3821,
      close: 3821,
      tickType: 'doji',
      tickLength: 0,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3821,
      time: '7613',
      x: 9,
      direction: ''
    },
    {
      tickLength: null,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      time: '71113',
      x: 10,
      direction: ''
    },
    {
      open: 3821,
      low: 3821,
      high: 3821,
      close: 3821,
      tickType: 'doji',
      tickLength: 0,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3821,
      time: '73113',
      x: 11,
      direction: ''
    },
    {
      tickLength: null,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      time: '73613',
      x: 12,
      direction: ''
    },
    {
      open: 3821,
      low: 3821,
      high: 3821,
      close: 3821,
      tickType: 'doji',
      tickLength: 0,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3821,
      time: '75613',
      x: 13,
      direction: ''
    },
    {
      tickLength: null,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      time: '8113',
      x: 14,
      direction: ''
    },
    {
      open: 3821,
      low: 3821,
      high: 3821,
      close: 3821,
      tickType: 'doji',
      tickLength: 0,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3821,
      time: '82113',
      x: 15,
      direction: ''
    },
    {
      tickLength: null,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      time: '82613',
      x: 16,
      direction: ''
    },
    {
      open: 3821,
      low: 3821,
      high: 3821,
      close: 3821,
      tickType: 'doji',
      tickLength: 0,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3821,
      time: '84113',
      x: 17,
      direction: ''
    },
    {
      tickLength: null,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      time: '84613',
      x: 18,
      direction: ''
    },
    {
      open: 3821,
      low: 3821,
      high: 3821,
      close: 3821,
      tickType: 'doji',
      tickLength: 0,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3821,
      time: '9613',
      x: 19,
      direction: ''
    },
    {
      tickLength: null,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      time: '91113',
      x: 20,
      direction: ''
    },
    {
      open: 3821,
      low: 3821,
      high: 3821,
      close: 3821,
      tickType: 'doji',
      tickLength: 0,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3821,
      time: '93113',
      x: 21,
      direction: ''
    },
    {
      tickLength: null,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      time: '93613',
      x: 22,
      direction: ''
    },
    {
      open: 3821,
      low: 3821,
      high: 3821,
      close: 3821,
      tickType: 'doji',
      tickLength: 0,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3821,
      time: '95113',
      x: 23,
      direction: ''
    },
    {
      tickLength: null,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      time: '95613',
      x: 24,
      direction: ''
    },
    {
      open: 3821,
      low: 3821,
      high: 3821,
      close: 3821,
      tickType: 'doji',
      tickLength: 0,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3821,
      time: '101613',
      x: 25,
      direction: ''
    },
    {
      tickLength: null,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      time: '102113',
      x: 26,
      direction: ''
    },
    {
      open: 3821,
      low: 3821,
      high: 3821,
      close: 3821,
      tickType: 'doji',
      tickLength: 0,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3821,
      time: '104113',
      x: 27,
      direction: ''
    },
    {
      tickLength: null,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      time: '104613',
      x: 28,
      direction: ''
    },
    {
      open: 3821,
      low: 3821,
      high: 3821,
      close: 3821,
      tickType: 'doji',
      tickLength: 0,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3821,
      time: '11113',
      x: 29,
      direction: ''
    },
    {
      tickLength: null,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      time: '11613',
      x: 30,
      direction: ''
    },
    {
      open: 3821,
      low: 3821,
      high: 3821,
      close: 3821,
      tickType: 'doji',
      tickLength: 0,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3821,
      time: '111613',
      x: 31,
      direction: ''
    },
    {
      tickLength: null,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      time: '112113',
      x: 32,
      direction: ''
    },
    {
      open: 3821,
      low: 3821,
      high: 3821,
      close: 3821,
      tickType: 'doji',
      tickLength: 0,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3821,
      time: '112613',
      x: 33,
      direction: ''
    },
    {
      open: 3706,
      low: 3703,
      high: 3713,
      close: 3711,
      tickType: 'green',
      tickLength: 10,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3703,
      time: '113113',
      x: 34,
      direction: 'down'
    },
    {
      open: 3711,
      low: 3701,
      high: 3713,
      close: 3709,
      tickType: 'red',
      tickLength: 12,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3701,
      time: '12113',
      x: 35,
      direction: 'down'
    },
    {
      open: 3703,
      low: 3697,
      high: 3705,
      close: 3697,
      tickType: 'red',
      tickLength: 8,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3697,
      time: '123113',
      x: 36,
      direction: 'down'
    },
    {
      open: 3697,
      low: 3682,
      high: 3698,
      close: 3697,
      tickType: 'doji',
      tickLength: 16,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3682,
      time: '123613',
      x: 37,
      direction: 'down'
    },
    {
      open: 3697,
      low: 3694,
      high: 3701,
      close: 3696,
      tickType: 'red',
      tickLength: 7,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3701,
      time: '124113',
      x: 38,
      direction: 'up'
    },
    {
      open: 3699,
      low: 3696,
      high: 3702,
      close: 3696,
      tickType: 'red',
      tickLength: 6,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3702,
      trend: 'upward',
      pivot: 3682,
      dir: 'low',
      currentPrice: 3696,
      time: '125113',
      x: 39,
      direction: 'up'
    },
    {
      open: 3696,
      low: 3691,
      high: 3701,
      close: 3694,
      tickType: 'red',
      tickLength: 10,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3691,
      time: '125613',
      x: 40,
      direction: 'down'
    },
    {
      open: 3694,
      low: 3685,
      high: 3697,
      close: 3692,
      tickType: 'red',
      tickLength: 12,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3685,
      trend: 'downtrend',
      pivot: 3702,
      dir: 'up',
      currentPrice: 3692,
      time: '13113',
      x: 41,
      direction: 'down'
    },
    {
      open: 3691,
      low: 3674,
      high: 3692,
      close: 3676,
      tickType: 'red',
      tickLength: 18,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3674,
      time: '13613',
      x: 42,
      direction: 'down'
    },
    {
      open: 3677,
      low: 3662,
      high: 3685,
      close: 3668,
      tickType: 'red',
      tickLength: 23,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3662,
      time: '131113',
      x: 43,
      direction: 'down'
    },
    {
      open: 3668,
      low: 3652,
      high: 3669,
      close: 3653,
      tickType: 'red',
      tickLength: 17,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3652,
      time: '131613',
      x: 44,
      direction: 'down'
    },
    {
      open: 3653,
      low: 3640,
      high: 3657,
      close: 3644,
      tickType: 'red',
      tickLength: 17,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3640,
      time: '132113',
      x: 45,
      direction: 'down'
    },
    {
      open: 3645,
      low: 3634,
      high: 3645,
      close: 3641,
      tickType: 'red',
      tickLength: 11,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3634,
      time: '132613',
      x: 46,
      direction: 'down'
    },
    {
      open: 3621,
      low: 3594,
      high: 3623,
      close: 3595,
      tickType: 'red',
      tickLength: 29,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3594,
      time: '133613',
      x: 47,
      direction: 'down'
    },
    {
      open: 3608,
      low: 3584,
      high: 3608,
      close: 3591,
      tickType: 'red',
      tickLength: 24,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3584,
      time: '135613',
      x: 48,
      direction: 'down'
    },
    {
      open: 3604,
      low: 3604,
      high: 3630,
      close: 3621,
      tickType: 'green',
      tickLength: 26,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3630,
      time: '14613',
      x: 49,
      direction: 'up'
    },
    {
      open: 3630,
      low: 3629,
      high: 3639,
      close: 3634,
      tickType: 'green',
      tickLength: 10,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3639,
      trend: 'upward',
      pivot: 3584,
      dir: 'low',
      currentPrice: 3634,
      time: '141613',
      x: 50,
      direction: 'up'
    },
    {
      open: 3630,
      low: 3618,
      high: 3644,
      close: 3641,
      tickType: 'green',
      tickLength: 26,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3644,
      time: '142613',
      x: 51,
      direction: 'up'
    },
    {
      open: 3643,
      low: 3635,
      high: 3649,
      close: 3637,
      tickType: 'red',
      tickLength: 14,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3649,
      time: '143113',
      x: 52,
      direction: 'up'
    },
    {
      open: 3637,
      low: 3629,
      high: 3644,
      close: 3634,
      tickType: 'red',
      tickLength: 15,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3629,
      time: '143613',
      x: 53,
      direction: 'down'
    },
    {
      open: 3634,
      low: 3616,
      high: 3638,
      close: 3620,
      tickType: 'red',
      tickLength: 22,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3616,
      trend: 'downtrend',
      pivot: 3649,
      dir: 'up',
      currentPrice: 3620,
      time: '144113',
      x: 54,
      direction: 'down'
    },
    {
      open: 3622,
      low: 3609,
      high: 3629,
      close: 3617,
      tickType: 'red',
      tickLength: 20,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3609,
      time: '144613',
      x: 55,
      direction: 'down'
    },
    {
      open: 3617,
      low: 3596,
      high: 3621,
      close: 3601,
      tickType: 'red',
      tickLength: 25,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3596,
      time: '145113',
      x: 56,
      direction: 'down'
    },
    {
      open: 3602,
      low: 3601,
      high: 3627,
      close: 3623,
      tickType: 'green',
      tickLength: 26,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3627,
      time: '145613',
      x: 57,
      direction: 'up'
    },
    {
      open: 3623,
      low: 3620,
      high: 3639,
      close: 3625,
      tickType: 'green',
      tickLength: 19,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3639,
      trend: 'upward',
      pivot: 3596,
      dir: 'low',
      currentPrice: 3625,
      time: '15113',
      x: 58,
      direction: 'up'
    },
    {
      open: 3630,
      low: 3615,
      high: 3632,
      close: 3616,
      tickType: 'red',
      tickLength: 17,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3615,
      time: '151113',
      x: 59,
      direction: 'down'
    },
    {
      open: 3616,
      low: 3608,
      high: 3622,
      close: 3615,
      tickType: 'red',
      tickLength: 14,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3608,
      trend: 'downtrend',
      pivot: 3639,
      dir: 'up',
      currentPrice: 3615,
      time: '151613',
      x: 60,
      direction: 'down'
    },
    {
      open: 3616,
      low: 3605,
      high: 3620,
      close: 3608,
      tickType: 'red',
      tickLength: 15,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3605,
      time: '152113',
      x: 61,
      direction: 'down'
    },
    {
      open: 3609,
      low: 3590,
      high: 3613,
      close: 3599,
      tickType: 'red',
      tickLength: 23,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3590,
      time: '152613',
      x: 62,
      direction: 'down'
    },
    {
      open: 3606,
      low: 3600,
      high: 3620,
      close: 3613,
      tickType: 'green',
      tickLength: 20,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3620,
      time: '153613',
      x: 63,
      direction: 'up'
    },
    {
      open: 3613,
      low: 3610,
      high: 3625,
      close: 3621,
      tickType: 'green',
      tickLength: 15,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3625,
      trend: 'upward',
      pivot: 3590,
      dir: 'low',
      currentPrice: 3621,
      time: '154113',
      x: 64,
      direction: 'up'
    },
    {
      open: 3621,
      low: 3603,
      high: 3622,
      close: 3605,
      tickType: 'red',
      tickLength: 19,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3603,
      time: '154613',
      x: 65,
      direction: 'down'
    },
    {
      open: 3605,
      low: 3598,
      high: 3609,
      close: 3608,
      tickType: 'green',
      tickLength: 11,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3598,
      trend: 'downtrend',
      pivot: 3625,
      dir: 'up',
      currentPrice: 3608,
      time: '155113',
      x: 66,
      direction: 'down'
    },
    {
      open: 3608,
      low: 3605,
      high: 3614,
      close: 3611,
      tickType: 'green',
      tickLength: 9,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3614,
      time: '155613',
      x: 67,
      direction: 'up'
    },
    {
      open: 3614,
      low: 3601,
      high: 3615,
      close: 3612,
      tickType: 'red',
      tickLength: 14,
      detecting: false,
      tradeStatus: 'not started',
      stop: 0,
      target: 0,
      shift: 0,
      y: 3615,
      trend: 'upward',
      pivot: 3598,
      dir: 'low',
      currentPrice: 3612,
      time: '16613',
      x: 68,
      direction: 'up'
    },
    {
      open: 3602,
      low: 3581,
      high: 3618,
      close: 3617,
      tickType: 'green',
      tickLength: 37,
      detecting: true,
      tradeStatus: 'start again',
      stop: 3597,
      target: 3652,
      shift: 0,
      y: 3618,
      time: '163116',
      x: 69,
      direction: 'up'
    }
  ]