{
  access: {},
  tickData: [
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3642,
      low: 3642,
      high: 3642,
      close: 3642,
      tickType: 'doji',
      tickLength: 0,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      trend: '',
      time: '22615',
      x: 1
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      tickLength: null,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      time: '23115',
      x: 2,
      direction: ''
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3642,
      low: 3642,
      high: 3642,
      close: 3642,
      tickType: 'doji',
      tickLength: 0,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3642,
      time: '31615',
      x: 3,
      direction: ''
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      tickLength: null,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      time: '32115',
      x: 4,
      direction: ''
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3642,
      low: 3642,
      high: 3642,
      close: 3642,
      tickType: 'doji',
      tickLength: 0,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3642,
      time: '33115',
      x: 5,
      direction: ''
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      tickLength: null,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      time: '33615',
      x: 6,
      direction: ''
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3642,
      low: 3642,
      high: 3642,
      close: 3642,
      tickType: 'doji',
      tickLength: 0,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3642,
      time: '35615',
      x: 7,
      direction: ''
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      tickLength: null,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      time: '4115',
      x: 8,
      direction: ''
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3642,
      low: 3642,
      high: 3642,
      close: 3642,
      tickType: 'doji',
      tickLength: 0,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3642,
      time: '42115',
      x: 9,
      direction: ''
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      tickLength: null,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      time: '42615',
      x: 10,
      direction: ''
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3693,
      low: 3693,
      high: 3698,
      close: 3696,
      tickType: 'green',
      tickLength: 5,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3696,
      time: '43115',
      x: 11,
      direction: ''
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3695,
      low: 3691,
      high: 3697,
      close: 3693,
      tickType: 'red',
      tickLength: 6,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3691,
      time: '43615',
      x: 12,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3696,
      low: 3694,
      high: 3698,
      close: 3694,
      tickType: 'red',
      tickLength: 4,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3698,
      time: '45115',
      x: 13,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3696,
      low: 3695,
      high: 3699,
      close: 3697,
      tickType: 'green',
      tickLength: 4,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3699,
      trend: 'upward',
      pivot: 3691,
      dir: 'low',
      currentPrice: 3697,
      time: '5615',
      x: 14,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3697,
      low: 3697,
      high: 3706,
      close: 3703,
      tickType: 'green',
      tickLength: 9,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3706,
      time: '51115',
      x: 15,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3698,
      low: 3693,
      high: 3699,
      close: 3693,
      tickType: 'red',
      tickLength: 6,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3693,
      time: '53615',
      x: 16,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3693,
      low: 3691,
      high: 3695,
      close: 3694,
      tickType: 'green',
      tickLength: 4,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3691,
      trend: 'downtrend',
      pivot: 3706,
      dir: 'up',
      currentPrice: 3694,
      time: '54115',
      x: 17,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3694,
      low: 3693,
      high: 3700,
      close: 3699,
      tickType: 'green',
      tickLength: 7,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3700,
      time: '55115',
      x: 18,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3699,
      low: 3698,
      high: 3703,
      close: 3700,
      tickType: 'green',
      tickLength: 5,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3703,
      trend: 'upward',
      pivot: 3691,
      dir: 'low',
      currentPrice: 3700,
      time: '55615',
      x: 19,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3700,
      low: 3700,
      high: 3709,
      close: 3703,
      tickType: 'green',
      tickLength: 9,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3709,
      time: '6115',
      x: 20,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3702,
      low: 3701,
      high: 3723,
      close: 3723,
      tickType: 'green',
      tickLength: 22,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3723,
      time: '62615',
      x: 21,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3705,
      low: 3698,
      high: 3705,
      close: 3700,
      tickType: 'red',
      tickLength: 7,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3698,
      time: '82615',
      x: 22,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3695,
      low: 3695,
      high: 3703,
      close: 3700,
      tickType: 'green',
      tickLength: 8,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3695,
      trend: 'downtrend',
      pivot: 3723,
      dir: 'up',
      currentPrice: 3700,
      time: '83615',
      x: 23,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3700,
      low: 3693,
      high: 3700,
      close: 3694,
      tickType: 'red',
      tickLength: 7,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3693,
      time: '84115',
      x: 24,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3695,
      low: 3689,
      high: 3695,
      close: 3692,
      tickType: 'red',
      tickLength: 6,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3689,
      time: '84615',
      x: 25,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3692,
      low: 3688,
      high: 3696,
      close: 3693,
      tickType: 'green',
      tickLength: 8,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3696,
      time: '85115',
      x: 26,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3693,
      low: 3692,
      high: 3699,
      close: 3696,
      tickType: 'green',
      tickLength: 7,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3699,
      trend: 'upward',
      pivot: 3689,
      dir: 'low',
      currentPrice: 3696,
      time: '9115',
      x: 27,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3696,
      low: 3683,
      high: 3696,
      close: 3686,
      tickType: 'red',
      tickLength: 13,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3683,
      time: '9615',
      x: 28,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3688,
      low: 3674,
      high: 3690,
      close: 3675,
      tickType: 'red',
      tickLength: 16,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3674,
      trend: 'downtrend',
      pivot: 3699,
      dir: 'up',
      currentPrice: 3675,
      time: '93115',
      x: 29,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3688,
      low: 3660,
      high: 3688,
      close: 3662,
      tickType: 'red',
      tickLength: 28,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3660,
      time: '102615',
      x: 30,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3661,
      low: 3657,
      high: 3666,
      close: 3662,
      tickType: 'green',
      tickLength: 9,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3657,
      time: '103115',
      x: 31,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3660,
      low: 3655,
      high: 3662,
      close: 3657,
      tickType: 'red',
      tickLength: 7,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3655,
      time: '104115',
      x: 32,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3658,
      low: 3652,
      high: 3663,
      close: 3659,
      tickType: 'green',
      tickLength: 11,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3663,
      time: '104615',
      x: 33,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3659,
      low: 3656,
      high: 3666,
      close: 3664,
      tickType: 'green',
      tickLength: 10,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3666,
      trend: 'upward',
      pivot: 3655,
      dir: 'low',
      currentPrice: 3664,
      time: '105115',
      x: 34,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3664,
      low: 3663,
      high: 3667,
      close: 3664,
      tickType: 'doji',
      tickLength: 4,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3667,
      time: '105615',
      x: 35,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3664,
      low: 3660,
      high: 3666,
      close: 3662,
      tickType: 'red',
      tickLength: 6,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3660,
      time: '11115',
      x: 36,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3661,
      low: 3655,
      high: 3662,
      close: 3657,
      tickType: 'red',
      tickLength: 7,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3655,
      trend: 'downtrend',
      pivot: 3667,
      dir: 'up',
      currentPrice: 3657,
      time: '11615',
      x: 37,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3657,
      low: 3643,
      high: 3657,
      close: 3651,
      tickType: 'red',
      tickLength: 14,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3643,
      time: '111115',
      x: 38,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3649,
      low: 3642,
      high: 3651,
      close: 3646,
      tickType: 'red',
      tickLength: 9,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3642,
      time: '113115',
      x: 39,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3646,
      low: 3640,
      high: 3647,
      close: 3645,
      tickType: 'red',
      tickLength: 7,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3640,
      time: '115115',
      x: 40,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3646,
      low: 3646,
      high: 3652,
      close: 3648,
      tickType: 'green',
      tickLength: 6,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3652,
      time: '115615',
      x: 41,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3648,
      low: 3646,
      high: 3656,
      close: 3654,
      tickType: 'green',
      tickLength: 10,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3656,
      trend: 'upward',
      pivot: 3640,
      dir: 'low',
      currentPrice: 3654,
      time: '12115',
      x: 42,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3655,
      low: 3654,
      high: 3663,
      close: 3661,
      tickType: 'green',
      tickLength: 9,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3663,
      time: '12615',
      x: 43,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3661,
      low: 3660,
      high: 3665,
      close: 3663,
      tickType: 'green',
      tickLength: 5,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3665,
      time: '121115',
      x: 44,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3663,
      low: 3663,
      high: 3670,
      close: 3666,
      tickType: 'green',
      tickLength: 7,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3670,
      time: '121615',
      x: 45,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3664,
      low: 3660,
      high: 3668,
      close: 3663,
      tickType: 'red',
      tickLength: 8,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3660,
      time: '123115',
      x: 46,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3663,
      low: 3655,
      high: 3664,
      close: 3657,
      tickType: 'red',
      tickLength: 9,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3655,
      trend: 'downtrend',
      pivot: 3670,
      dir: 'up',
      currentPrice: 3657,
      time: '123615',
      x: 47,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3658,
      low: 3650,
      high: 3658,
      close: 3650,
      tickType: 'red',
      tickLength: 8,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3650,
      time: '124615',
      x: 48,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3650,
      low: 3645,
      high: 3652,
      close: 3646,
      tickType: 'red',
      tickLength: 7,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3645,
      time: '125115',
      x: 49,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3647,
      low: 3640,
      high: 3648,
      close: 3640,
      tickType: 'red',
      tickLength: 8,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3640,
      time: '13115',
      x: 50,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3648,
      low: 3635,
      high: 3648,
      close: 3638,
      tickType: 'red',
      tickLength: 13,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3635,
      time: '131115',
      x: 51,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3638,
      low: 3626,
      high: 3640,
      close: 3627,
      tickType: 'red',
      tickLength: 14,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3626,
      time: '131615',
      x: 52,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3629,
      low: 3621,
      high: 3633,
      close: 3629,
      tickType: 'doji',
      tickLength: 12,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3621,
      time: '133115',
      x: 53,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3628,
      low: 3618,
      high: 3630,
      close: 3621,
      tickType: 'red',
      tickLength: 12,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3618,
      time: '133615',
      x: 54,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3622,
      low: 3612,
      high: 3623,
      close: 3614,
      tickType: 'red',
      tickLength: 11,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3612,
      time: '134615',
      x: 55,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3614,
      low: 3609,
      high: 3616,
      close: 3613,
      tickType: 'red',
      tickLength: 7,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3609,
      time: '135115',
      x: 56,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3613,
      low: 3613,
      high: 3627,
      close: 3626,
      tickType: 'green',
      tickLength: 14,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3627,
      time: '135615',
      x: 57,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3625,
      low: 3623,
      high: 3633,
      close: 3630,
      tickType: 'green',
      tickLength: 10,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3633,
      trend: 'upward',
      pivot: 3609,
      dir: 'low',
      currentPrice: 3630,
      time: '14115',
      x: 58,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3633,
      low: 3624,
      high: 3635,
      close: 3631,
      tickType: 'red',
      tickLength: 11,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3635,
      time: '14615',
      x: 59,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3630,
      low: 3628,
      high: 3638,
      close: 3631,
      tickType: 'green',
      tickLength: 10,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3638,
      time: '141615',
      x: 60,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3625,
      low: 3617,
      high: 3645,
      close: 3645,
      tickType: 'green',
      tickLength: 28,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3645,
      time: '143615',
      x: 61,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3646,
      low: 3630,
      high: 3651,
      close: 3630,
      tickType: 'red',
      tickLength: 21,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3651,
      time: '144115',
      x: 62,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3630,
      low: 3606,
      high: 3633,
      close: 3607,
      tickType: 'red',
      tickLength: 27,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3606,
      time: '144615',
      x: 63,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3605,
      low: 3605,
      high: 3623,
      close: 3620,
      tickType: 'green',
      tickLength: 18,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3605,
      trend: 'downtrend',
      pivot: 3651,
      dir: 'up',
      currentPrice: 3620,
      time: '145115',
      x: 64,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3620,
      low: 3614,
      high: 3624,
      close: 3614,
      tickType: 'red',
      tickLength: 10,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3624,
      time: '145615',
      x: 65,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3620,
      low: 3619,
      high: 3629,
      close: 3628,
      tickType: 'green',
      tickLength: 10,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3629,
      trend: 'upward',
      pivot: 3605,
      dir: 'low',
      currentPrice: 3628,
      time: '151615',
      x: 66,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3628,
      low: 3622,
      high: 3633,
      close: 3631,
      tickType: 'green',
      tickLength: 11,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3633,
      time: '152115',
      x: 67,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3613,
      low: 3591,
      high: 3644,
      close: 3638,
      tickType: 'green',
      tickLength: 53,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3644,
      time: '153615',
      x: 68,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3639,
      low: 3616,
      high: 3650,
      close: 3634,
      tickType: 'red',
      tickLength: 34,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3650,
      time: '154115',
      x: 69,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3623,
      low: 3613,
      high: 3626,
      close: 3613,
      tickType: 'red',
      tickLength: 13,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3613,
      time: '155615',
      x: 70,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3611,
      low: 3608,
      high: 3620,
      close: 3610,
      tickType: 'red',
      tickLength: 12,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3608,
      trend: 'downtrend',
      pivot: 3650,
      dir: 'up',
      currentPrice: 3610,
      time: '16115',
      x: 71,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3610,
      low: 3596,
      high: 3610,
      close: 3600,
      tickType: 'red',
      tickLength: 14,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3596,
      time: '16615',
      x: 72,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3600,
      low: 3600,
      high: 3613,
      close: 3613,
      tickType: 'green',
      tickLength: 13,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3613,
      time: '161115',
      x: 73,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3613,
      low: 3611,
      high: 3630,
      close: 3616,
      tickType: 'green',
      tickLength: 19,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3630,
      trend: 'upward',
      pivot: 3596,
      dir: 'low',
      currentPrice: 3616,
      time: '161615',
      x: 74,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3610,
      low: 3610,
      high: 3637,
      close: 3635,
      tickType: 'green',
      tickLength: 27,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3637,
      time: '163115',
      x: 75,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3635,
      low: 3635,
      high: 3663,
      close: 3661,
      tickType: 'green',
      tickLength: 28,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3663,
      time: '163615',
      x: 76,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3661,
      low: 3651,
      high: 3667,
      close: 3654,
      tickType: 'red',
      tickLength: 16,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3667,
      time: '164115',
      x: 77,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3653,
      low: 3653,
      high: 3668,
      close: 3663,
      tickType: 'green',
      tickLength: 15,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3668,
      time: '164615',
      x: 78,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3657,
      low: 3655,
      high: 3671,
      close: 3670,
      tickType: 'green',
      tickLength: 16,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3671,
      time: '17115',
      x: 79,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3669,
      low: 3664,
      high: 3693,
      close: 3686,
      tickType: 'green',
      tickLength: 29,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3693,
      time: '17615',
      x: 80,
      direction: 'up'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3675,
      low: 3657,
      high: 3675,
      close: 3662,
      tickType: 'red',
      tickLength: 18,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3657,
      time: '171615',
      x: 81,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3662,
      low: 3655,
      high: 3672,
      close: 3671,
      tickType: 'green',
      tickLength: 17,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3655,
      trend: 'downtrend',
      pivot: 3693,
      dir: 'up',
      currentPrice: 3671,
      time: '172115',
      x: 82,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3671,
      low: 3653,
      high: 3671,
      close: 3654,
      tickType: 'red',
      tickLength: 18,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3653,
      time: '172615',
      x: 83,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3654,
      low: 3650,
      high: 3664,
      close: 3659,
      tickType: 'green',
      tickLength: 14,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3650,
      time: '173115',
      x: 84,
      direction: 'down'
    },
    {
      stop: 0,
      target: 0,
      shift: 0,
      open: 3653,
      low: 3642,
      high: 3655,
      close: 3646,
      tickType: 'red',
      tickLength: 13,
      date: '',
      detecting: false,
      tradeStatus: 'not started',
      y: 3642,
      time: '174615',
      x: 85,
      direction: 'down'
    }
  ],
  plData: [
    {
      x: 0,
      y: 3642
    },
    {
      x: 1,
      y: 3691,
      dir: 'low',
      date: '',
      currentPrice: 3697,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      lowest: 3642,
      highest: 3691,
      sidecount: 0
    },
    {
      x: 2,
      y: 3706,
      dir: 'up',
      date: '',
      currentPrice: 3694,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      highest: 3691,
      lowest: 3642,
      sidecount: 1,
      upcount: 1,
      upblackextreme: 3706,
      upblackextremeindex: 2
    },
    {
      x: 3,
      y: 3691,
      dir: 'low',
      date: '',
      currentPrice: 3700,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 1,
      highest: 3691,
      lowest: 3642,
      upblackextreme: 3706,
      upblackextremeindex: 2,
      sidecount: 2
    },
    {
      x: 4,
      y: 3723,
      dir: 'up',
      date: '',
      currentPrice: 3700,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      highest: 3723,
      lowest: 3691,
      upblackextreme: 0,
      upblackextremeindex: 2,
      downcount: 0,
      sidecount: 0,
      lowblackextreme: 0,
      UPblackpoint: 0,
      Lowblackpoint: 0
    },
    {
      x: 5,
      y: 3689,
      dir: 'low',
      date: '',
      currentPrice: 3696,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3723,
      lowest: 3691,
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 0,
      upblackextremeindex: 2,
      sidecount: 1
    },
    {
      x: 6,
      y: 3699,
      dir: 'up',
      date: '',
      currentPrice: 3675,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3723,
      lowest: 3691,
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 0,
      upblackextremeindex: 2,
      sidecount: 2
    },
    {
      x: 7,
      y: 3655,
      dir: 'low',
      date: '',
      currentPrice: 3664,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3699,
      lowest: 3655,
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 0,
      upblackextremeindex: 2,
      sidecount: 0
    },
    {
      x: 8,
      y: 3667,
      dir: 'up',
      date: '',
      currentPrice: 3657,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3699,
      lowest: 3655,
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 0,
      upblackextremeindex: 2,
      sidecount: 1
    },
    {
      x: 9,
      y: 3640,
      dir: 'low',
      date: '',
      currentPrice: 3654,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 1,
      highest: 3699,
      lowest: 3655,
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 3640,
      upblackextreme: 0,
      upblackextremeindex: 2,
      sidecount: 2,
      lowblackextremeindex: 9
    },
    {
      x: 10,
      y: 3670,
      dir: 'up',
      date: '',
      currentPrice: 3657,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 1,
      highest: 3699,
      lowest: 3655,
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 3640,
      upblackextreme: 0,
      upblackextremeindex: 2,
      lowblackextremeindex: 9,
      sidecount: 3
    },
    {
      x: 11,
      y: 3609,
      dir: 'low',
      date: '',
      currentPrice: 3630,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3670,
      lowest: 3609,
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 3640,
      upblackextreme: 0,
      upblackextremeindex: 2,
      lowblackextremeindex: 9,
      sidecount: 0
    },
    {
      x: 12,
      y: 3651,
      dir: 'up',
      date: '',
      currentPrice: 3620,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3670,
      lowest: 3609,
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 3640,
      upblackextreme: 0,
      upblackextremeindex: 2,
      lowblackextremeindex: 9,
      sidecount: 1
    },
    {
      x: 13,
      y: 3605,
      dir: 'low',
      date: '',
      currentPrice: 3628,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3670,
      lowest: 3609,
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 3640,
      upblackextreme: 0,
      upblackextremeindex: 2,
      lowblackextremeindex: 9,
      sidecount: 2
    },
    {
      x: 14,
      y: 3650,
      dir: 'up',
      date: '',
      currentPrice: 3610,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3670,
      lowest: 3609,
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 3640,
      upblackextreme: 0,
      upblackextremeindex: 2,
      lowblackextremeindex: 9,
      sidecount: 3
    },
    {
      x: 15,
      y: 3596,
      dir: 'low',
      date: '',
      currentPrice: 3616,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 1,
      highest: 3670,
      lowest: 3609,
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 3596,
      upblackextreme: 0,
      upblackextremeindex: 2,
      lowblackextremeindex: 15,
      sidecount: 4,
      trend: 'sideways'
    },
    {
      x: 16,
      y: 3693,
      dir: 'up',
      date: '',
      currentPrice: 3671,
      tradeStatus: 'not started',
      crudeTradePrice: 0,
      crudeTradeManagement: false,
      upcount: 0,
      downcount: 0,
      highest: 3693,
      lowest: 3596,
      trend: 'sideways',
      UPblackpoint: 0,
      Lowblackpoint: 0,
      lowblackextreme: 0,
      upblackextreme: 0,
      upblackextremeindex: 2,
      lowblackextremeindex: 15,
      bigDayTrade: 'short',
      bigDayTradePrice: 3693,
      sidecount: 0
    }
  ],
  tickDataTest: [],
  plDataTest: [],
  plDataNifty: [],
  tickDataNifty: [],
  plDataNickle: [],
  tickDataNickle: [],
  tickDataJD: [],
  tickDataTCS: [],
  plDataTCS: []
}